PhpMob\CmsBundle\Model\PageTranslation:
    type: mappedSuperclass
    table: changmin_cms_page_translation

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    indexes:
        IDX_SLUGS:
            columns:
                - slug
                - locale

    fields:
        title:
            type: string
            nullable: true
        slug:
            type: string
            nullable: true
        body:
            type: text
            nullable: true
        metaDescription:
            type: string
            nullable: true
        metaKeywords:
            type: string
            nullable: true
