phpmob_cms_page_view:
    path: /{slug}
    methods: [ GET ]
    requirements:
        slug: "[^/]+"
    defaults:
        _controller: phpmob.controller.page:viewAction
        _sylius:
            event: page_view
            flash: flase
            permission: false
            template: "@PhpMobCms/page.html.twig"
            repository:
                method: findOneBySlug
                arguments: [ $slug ]
