imports:
    - { resource: "services/**" }

services:
    phpmob.locale.add_defined_translation:
        class: PhpMob\CmsBundle\Translation\AddDefinedTranslation
        public: true
        arguments:
            - '@sylius.context.locale'
            - '@translator'

    chang.locale.translatable_entity_assigner:
        class: PhpMob\CmsBundle\Translation\TranslatableEntityLocaleAssigner
        decorates: sylius.translatable_entity_locale_assigner
        arguments:
            - '@service_container'
