sylius_grid:
    grids:
        admin_page_grid:
            driver:
                name: doctrine/orm
                options:
                    class: "%phpmob.model.page.class%"
                    repository:
                        method: createLocaledQueryBuilder
                        arguments: [ 'expr:service("sylius.context.locale").getLocaleCode()' ]
            limits: [20]
            sorting:
                createdAt: desc
            fields:
                enabled:
                    type: toggle
                    label: chang.ui.enabled
                    sortable: ~
                    options:
                        route: phpmob_page_toggle
                        parameters: { id: '@id' }
                        on_label: 'chang.ui.enabled'
                        off_label: 'chang.ui.disabled'
                title:
                    type: text
                    label: Title
                    sortable: translation.title
                    options:
                        width: auto
                template:
                    type: tpl
                    label: Template
                    sortable: false
                    path: template
                    options:
                        width: auto
                        template: "@PhpMobCms/Template/Grid/Field/name.html.twig"
                createdAt:
                    type: localizeddate
                    label: Created At
                    sortable: ~
                updatedAt:
                    type: localizeddate
                    label: Updated At
                    sortable: ~
            filters:
                title:
                    type: string
                    label: Title
                    options:
                        default: true
                        fields:
                            - translation.title
                body:
                    type: string
                    label: Body
                    options:
                        fields:
                            - translation.body
                metaDescription:
                    type: string
                    label: Meta Description
                    options:
                        fields:
                            - translation.metaDescription
                metaKeywords:
                    type: string
                    label: Meta Keywords
                    options:
                        fields:
                            - translation.metaKeywords
            actions:
                main:
                    create:
                        icon: fa fa-plus
                        label: Create Page
                        type: create
                item:
                    update:
                        type: update
                    show:
                        type: show
                    delete:
                        type: delete
