fos_ck_editor:
    default_config: default
    configs:
        default:
            toolbar: standard
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters:
                instance: phpmob_cms
