phpmob_page_index:
    path: /pages
    methods: [ GET ]
    defaults:
        _controller: phpmob.controller.page:indexAction
        _sylius:
            template: base/crud/index.html.twig
            grid: admin_page_grid
            vars:
                icon: far fa-file-alt

phpmob_page_create:
    path: /pages/create
    methods: [ GET, POST ]
    defaults:
        _controller: phpmob.controller.page:createAction
        _sylius:
            form: PhpMob\CmsBundle\Form\Type\PageType
            template: base/crud/create.html.twig
            vars:
                templates:
                    form: '@PhpMobCms/Page/_form.html.twig'

phpmob_page_update:
    path: /pages/{id}/update
    methods: [ GET, PATCH, PUT ]
    defaults:
        _controller: phpmob.controller.page:updateAction
        _sylius:
            form: PhpMob\CmsBundle\Form\Type\PageType
            template: base/crud/update.html.twig
            vars:
                templates:
                    form: '@PhpMobCms/Page/_form.html.twig'

phpmob_page_delete:
    path: /pages/{id}/delete
    methods: [ DELETE ]
    defaults:
        _controller: phpmob.controller.page:deleteAction
