phpmob_page_index:
    path: /
    methods: [ GET ]
    defaults:
        _controller: phpmob.controller.page:indexAction
        _sylius:
            template: '@chang/crud/index.html.twig'
            grid: admin_page_grid
            vars:
                icon: far fa-file-alt

phpmob_page_create:
    path: /create
    methods: [ GET, POST ]
    defaults:
        _controller: phpmob.controller.page:createAction
        _sylius:
            form: PhpMob\CmsBundle\Form\Type\PageType
            template: '@chang/crud/create.html.twig'
            vars:
                templates:
                    form: '@PhpMobCms/Page/_form.html.twig'

phpmob_page_update:
    path: /{id}/update
    methods: [ GET, PATCH, PUT ]
    defaults:
        _controller: phpmob.controller.page:updateAction
        _sylius:
            form: PhpMob\CmsBundle\Form\Type\PageType
            template: '@chang/crud/update.html.twig'
            vars:
                templates:
                    form: '@PhpMobCms/Page/_form.html.twig'

phpmob_page_delete:
    path: /{id}/delete
    methods: [ DELETE ]
    defaults:
        _controller: phpmob.controller.page:deleteAction

phpmob_page_toggle:
    path: /{id}/toggle
    methods: [ PATCH ]
    defaults:
        _controller: phpmob.controller.page:updateAction
        _sylius:
            form:
                type: Chang\AdminUser\Form\Type\ToggleResourceType
                options:
                    data_class: '%phpmob.model.page.class%'
