phpmob_template_index:
    path: /
    methods: [ GET ]
    defaults:
        _controller: phpmob.controller.template:indexAction
        _sylius:
            template: '@chang/crud/index.html.twig'
            grid: admin_template_grid
            vars:
                icon: fas fa-code

phpmob_template_create:
    path: /create
    methods: [ GET, POST ]
    defaults:
        _controller: phpmob.controller.template:createAction
        _sylius:
            form: PhpMob\CmsBundle\Form\Type\TemplateType
            template: '@chang/crud/create.html.twig'
            vars:
                templates:
                    form: '@PhpMobCms/Template/_form.html.twig'

phpmob_template_update:
    path: /{id}/update
    methods: [ GET, PATCH, PUT ]
    defaults:
        _controller: phpmob.controller.template:updateAction
        _sylius:
            form: PhpMob\CmsBundle\Form\Type\TemplateType
            template: '@chang/crud/update.html.twig'
            vars:
                templates:
                    form: '@PhpMobCms/Template/_form.html.twig'

phpmob_template_delete:
    path: /{id}/delete
    methods: [ DELETE ]
    defaults:
        _controller: phpmob.controller.template:deleteAction
